version: '3'

services:
  reconnection-service-standalone:
    # container_name: reconnection-service-standalone
    image: amplicalabs/reconnection-service:standalone-latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    networks:
      - reconnection-service-network-dev
    # volumes:
    # - redis_data:/var/lib/redis

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    container_name: redis
    networks:
      - reconnection-service-network-dev
    volumes:
      - redis_data:/data

  frequency:
    image: dsnp/instant-seal-node-with-deployed-schemas:latest
    environment:
      - SEALING_MODE=interval
      - SEALING_INTERVAL=3
      - CREATE_EMPTY_BLOCKS=true
    hostname: frequency
    ports:
      - 9944:9944
    networks:
      - reconnection-service-network-dev
    container_name: frequency-interval
    volumes:
      - chainstorage:/data

  frequency-instant:
    image: dsnp/instant-seal-node-with-deployed-schemas:latest
    environment:
      - SEALING_MODE=instant
    hostname: frequency
    ports:
      - 9944:9944
    networks:
      - reconnection-service-network-dev
    container_name: frequency-instant
    volumes:
      - chainstorage:/data

  webhook:
    container_name: webhook
    hostname: webhook
    build:
      context: .
      dockerfile: webhook-specification/mock-webhook-server/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./webhook-specification/mock-webhook-server:/app
    networks:
      - reconnection-service-network-dev

  reconnection-service:
    depends_on:
      - redis
      - frequency-instant
      - webhook
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.docker.dev
    volumes:
    - ./:/app
    networks:
      - reconnection-service-network-dev

volumes:
  redis_data:
  chainstorage:
    external: false

networks:
  reconnection-service-network-dev:
